# Generated by Django 4.0.10 on 2023-05-25 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_topik', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ketersediaan', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia')], default='Tersedia', max_length=20)),
                ('pengerjaan', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('content', models.TextField(max_length=2048)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('bidangs', models.ManyToManyField(blank=True, related_name='+', to='topik.bidang')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
