# Generated by Django 4.0.10 on 2023-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidang',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='short',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
