stages:
  - lint

variables:
  POSTGRES_USER: 'sipeta_backend'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_sipeta_backend'
  POSTGRES_HOST_AUTH_METHOD: trust

precommit:
  stage: lint
  image: python:3.10
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files
