# Generated by Django 4.0.10 on 2023-05-15 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sipeta_backend.proposal.models
import sipeta_backend.proposal.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposal', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sumber_ide', models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen'), ('MKM', 'MKM')], default='Mahasiswa', max_length=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ditolak', 'Ditolak'), ('Diterima', 'Diterima'), ('Dibatalkan', 'Dibatalkan')], default='Pending', max_length=20)),
                ('berkas_proposal', models.FileField(upload_to=sipeta_backend.proposal.models.hash_filename_presentasi, validators=[sipeta_backend.proposal.validators.validate_file_size, sipeta_backend.proposal.validators.validate_file_extension])),
                ('nama_berkas_proposal', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dosen_pembimbings', models.ManyToManyField(blank=True, related_name='%(class)s_pembimbing', to=settings.AUTH_USER_MODEL)),
                ('dosen_tertariks', models.ManyToManyField(blank=True, related_name='%(class)s_tertarik', to=settings.AUTH_USER_MODEL)),
                ('mahasiswas', models.ManyToManyField(related_name='%(class)s_mahasiswa', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='semester.semester')),
            ],
            options={
                'ordering': ['-semester', '-created_on'],
            },
        ),
    ]
