# Generated by Django 4.0.10 on 2023-05-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['semester', '-created_on']},
        ),
    ]
