# Generated by Django 4.0.10 on 2023-05-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0003_administrasiproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraksiProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('CMT', 'Komentar'), ('CSP', 'Change Status Proposal'), ('CDP', 'Change Dosen Pembimbing'), ('EJP', 'Edit Judul Proposal'), ('EBP', 'Edit Berkas Proposal')], max_length=3)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
