# Generated by Django 4.0.10 on 2023-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_interaksiproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ditolak', 'Ditolak'), ('Disetujui', 'Disetujui'), ('Dibatalkan', 'Dibatalkan')], default='Pending', max_length=20),
        ),
    ]
