# Proposal.status
PROPOSAL_STATUS_PENDING = "Pending"
PROPOSAL_STATUS_DITOLAK = "Ditolak"
PROPOSAL_STATUS_DITERIMA = "Diterima"
PROPOSAL_STATUS_DIBATALKAN = "Dibatalkan"

PROPOSAL_STATUS_CHOICES = (
    (PROPOSAL_STATUS_PENDING, "Pending"),
    (PROPOSAL_STATUS_DITOLAK, "Ditolak"),
    (PROPOSAL_STATUS_DITERIMA, "Diterima"),
    (PROPOSAL_STATUS_DIBATALKAN, "Dibatalkan"),
)

# Proposal.sumber_ide
PROPOSAL_SUMBER_IDE_MAHASISWA = "Mahasiswa"
PROPOSAL_SUMBER_IDE_DOSEN = "Dosen"
PROPOSAL_SUMBER_IDE_MKM = "MKM"

PROPOSAL_SUMBER_IDE_CHOICES = (
    (PROPOSAL_SUMBER_IDE_MAHASISWA, "Mahasiswa"),
    (PROPOSAL_SUMBER_IDE_DOSEN, "Dosen"),
    (PROPOSAL_SUMBER_IDE_MKM, "MKM"),
)
