# Generated by Django 4.0.10 on 2023-05-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sipeta_backend.pengumuman.models
import sipeta_backend.pengumuman.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengumuman', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=2048)),
                ('lampiran', models.FileField(blank=True, upload_to=sipeta_backend.pengumuman.models.hash_filename_lampiran, validators=[sipeta_backend.pengumuman.validators.validate_file_size, sipeta_backend.pengumuman.validators.validate_file_extension])),
                ('nama_lampiran', models.CharField(blank=True, max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='semester.semester')),
            ],
            options={
                'ordering': ['semester', '-created_on'],
            },
        ),
    ]
