# Generated by Django 4.0.10 on 2023-05-10 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dosen_eksternal',
            field=models.BooleanField(default=False, verbose_name='Dosen Eksternal'),
        ),
        migrations.AddField(
            model_name='user',
            name='kode_identitas',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kode Identitas'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_pengguna',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role Pengguna'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Lengkap'),
        ),
    ]
