# Generated by Django 4.0.10 on 2023-05-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_user_user_is_dosen_eksternal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dosen_ta',
            field=models.BooleanField(default=False, verbose_name='Dosen TA'),
        ),
    ]
