# Generated by Django 4.0.10 on 2023-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_dosen_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program_studi',
            field=models.CharField(blank=True, choices=[('S1 Ilkom Reguler', 'S1 Ilkom Reguler'), ('S1 Ilkom Paralel', 'S1 Ilkom Paralel'), ('S1 Ilkom KI', 'S1 Ilkom KI'), ('S1 SI Reguler', 'S1 SI Reguler'), ('S1 SI Paralel', 'S1 SI Paralel'), ('S1 SI Ekstensi', 'S1 SI Ekstensi')], max_length=60, verbose_name='Program Studi'),
        ),
    ]
