# Generated by Django 4.0.10 on 2023-05-15 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_semester', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('GENAP', 'GENAP'), ('GASAL', 'GASAL'), ('PENDEK', 'PENDEK')], default='GENAP', max_length=10)),
                ('periode', models.CharField(default='2022/2023', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-periode', '-semester'],
                'unique_together': {('semester', 'periode')},
            },
        ),
    ]
